version: '3'

networks:
  app:

services:
  workspace:
    build:
      context: ./workspace
    image: ${COMPOSE_PROJECT_NAME}_workspace:latest
    volumes:
      - ../:/var/www/html
    tty: true
    networks:
      app:

  nginx:
    build:
      context: ./nginx
    image: ${COMPOSE_PROJECT_NAME}_nginx:latest
    volumes:
      - ../public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      app:
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_php-fpm:latest
    volumes:
      - ../:/var/www/html
    networks:
      app:

  php-cli:
    build:
      context: ./php-cli
    image: ${COMPOSE_PROJECT_NAME}_php_cli:latest
    volumes:
      - ../:/app
    networks:
      app:

  mariadb:
    build:
      context: ./mariadb
    image: ${COMPOSE_PROJECT_NAME}_mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${MARIA_DATABASE}
      - MYSQL_USER=${MARIA_USER}
      - MYSQL_PASSWORD=${MARIA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
    networks:
      app:
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./mariadb/init.d:/docker-entrypoint-init.d